# Generated by Django 5.2.10 on 2026-01-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_hired',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
